version: '2'
services:
  blog:
    build: .
    image: blog:1.0
    container_name: blog
    command: make prod
    restart: always
    env_file: .env
    volumes:
      - /var/run/postgresql:/run/postgresql
      - ${VOLUME_PATH}/log:/www/log
      - ${VOLUME_PATH}/public:/www/blog/public/volume
    ports:
      - "8000:8000"
    networks:
      - blog

networks:
  blog:
