version: '2'
services:
  blog:
    build: .
    container_name: blog
    command: /usr/local/bin/gunicorn app:app -b 0.0.0.0:8000 -c /blog/configs/gunicorn_conf.py
    restart: on-failure
    environment:
      DB_USER: '${DB_USER}'
      DB_PASS: '${DB_PASS}'
      DB_ADDRESS: '${DB_ADDRESS}'
      FLASK_SALT: '${FLASK_SALT}'
      FLASK_SECRET: '${FLASK_SECRET}'
    volumes:
      - /var/run/postgresql:/run/postgresql
      - /home/uploads:/blog/app/static/uploads
    ports:
      - "8000:8000"